name: Deploy index.html to EC2

on:
  push:
    paths:
      - "site/index.html"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy index.html to EC2 tmp folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "index.html"
          target: "/tmp/deploy"

      - name: Move index.html into nginx folder with sudo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo mv /tmp/deploy/index.html /usr/share/nginx/html/index.html
            sudo chown nginx:nginx /usr/share/nginx/html/index.html

